# Generated by Django 5.2.7 on 2026-01-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(blank=True, max_length=14, null=True, verbose_name='Numéro SIRET 14 chiffres')),
                ('clients_type', models.CharField(choices=[('individuals', 'Particulier'), ('business', 'Entreprise')], max_length=255, verbose_name='Type de client')),
                ('name_organisation', models.CharField(max_length=255, verbose_name='Nom ou raison sociale')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nom de famille')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone mobile')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email de connexion')),
                ('name_business', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe (hashé)')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp de modification')),
                ('last_login', models.DateField(blank=True, null=True, verbose_name='Dernière connexion')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_et', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix HT (ET = Excluding Tax)')),
                ('price_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TVA (VAT)')),
                ('price_ati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix TTC (ATI = All Taxes Included)')),
                ('sent', models.BooleanField(default=False, verbose_name='Envoyé au client ?')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.DateField(blank=True, null=True)),
                ('clients_id', models.ForeignKey(db_column='clients_id', on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='app.clients', verbose_name='Client')),
                ('users_id', models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='app.users', verbose_name='Créé par <django.db.models.query_utils.DeferredAttribute object at 0x7c5c9fd34310>')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='EstimateLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('line_type', models.CharField(blank=True, choices=[('benefit', 'Prestation'), ('supply', 'Fourniture')], max_length=255, null=True, verbose_name='Type de ligne')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('rate_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de TVA (%)')),
                ('amount_et', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant HT')),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Note')),
                ('estimates_id', models.ForeignKey(db_column='estimates_id', on_delete=django.db.models.deletion.CASCADE, related_name='estimate_lines', to='app.estimates', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'db_table': 'estimate_lines',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True, verbose_name='Numéro de facture')),
                ('price_et', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix HT')),
                ('price_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TVA')),
                ('price_ati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix TTC')),
                ('sent', models.BooleanField(default=False, verbose_name='Envoyé au client ?')),
                ('sent_date', models.DateField(verbose_name="Date d'envoi")),
                ('payements_method', models.CharField(choices=[('CB', 'Carte Bancaire'), ('Virement', 'Virement'), ('espèce', 'Espèces')], max_length=255, verbose_name='Mode de paiement')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Date de modification')),
                ('clients_id', models.ForeignKey(db_column='clients_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.clients', verbose_name='Client')),
                ('users_id', models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.users', verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('line_type', models.CharField(blank=True, choices=[('benefit', 'Prestation'), ('supply', 'Fourniture')], max_length=255, null=True, verbose_name='Type de ligne')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('taux_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de TVA (%)')),
                ('amount_et', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant HT')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='app.invoices', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'invoice_lines',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='users_id',
            field=models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.users'),
        ),
    ]
