# Generated by Django 5.2.7 on 2026-01-20 21:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name_business', models.CharField(blank=True, default='', max_length=255, verbose_name="Nom de l'entreprise")),
                ('siret', models.CharField(blank=True, default='', max_length=14, verbose_name='Numéro SIRET (14 chiffres)')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Code postal')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone mobile')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'app_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individuals', 'Particulier'), ('business', 'Entreprise')], max_length=20, verbose_name='Type de client')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone mobile')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Prénom (particulier)')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom (particulier)')),
                ('name_organisation', models.CharField(blank=True, default='', max_length=255, verbose_name="Nom de l'entreprise")),
                ('siret', models.CharField(blank=True, default='', max_length=14, verbose_name='Numéro SIRET (entreprise)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=20, verbose_name='Statut')),
                ('price_et', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Prix HT')),
                ('price_vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='TVA')),
                ('price_ati', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Prix TTC')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='app.client', verbose_name='Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('line_type', models.CharField(blank=True, choices=[('benefit', 'Prestation'), ('supply', 'Fourniture')], default='benefit', max_length=20, verbose_name='Type de ligne')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('price_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('rate_vat', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('amount_et', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant HT')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_line', to='app.estimate', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'db_table': 'estimate_lines',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('price_et', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix HT')),
                ('price_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA')),
                ('price_ati', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TTC')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('payment_method', models.CharField(blank=True, choices=[('CB', 'Carte Bancaire'), ('Virement', 'Virement'), ('Espece', 'Espèces'), ('Cheque', 'Chèque')], default='', max_length=50, verbose_name='Mode de paiement')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='app.client', verbose_name='Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('line_type', models.CharField(blank=True, choices=[('benefit', 'Prestation'), ('supply', 'Fourniture')], default='benefit', max_length=20, verbose_name='Type de ligne')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('price_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('taux_vat', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('amount_et', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant HT')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line', to='app.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'invoice_lines',
            },
        ),
    ]
