# Generated by Django 5.2.7 on 2026-01-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_estimates_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='users',
            field=models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='app.users', verbose_name='Créé par <django.db.models.query_utils.DeferredAttribute object at 0x000002247A576490>'),
        ),
    ]
