# Generated by Django 5.2.7 on 2025-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoice_statistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='domaine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(max_length=20),
        ),
    ]
